project:
  type: website
 
  
  

website:
  title: "akmsquarto"
  reader-mode: true
  page-navigation: true
  
  page-footer:
    center: "Built with ❤️ and powered by Quarto"
    left: "&copy; CC-By CWB, 2024"
    
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - sidebar:tutorials
      - sidebar:howto
      - sidebar:fundamentals
      - sidebar:reference
  #######################
  #####sidebar###########
  #######################
  sidebar:
    logo: "images/cwd/1.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://github.com/arunmhh
        text: "arunmhh"
      - icon: github
        href: https://github.com/arunmhh/akmsquarto
        text: "Quartoarun"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Quartoinformation
      - href: linearregression.qmd
        text: linear regression
      - section: quarto-workflows/index.qmd
        contents: 
          - quarto-workflows/browser.md
          - quarto-workflows/rstudio.qmd
          - quarto-workflows/jupyter.md 
      - learning-more.qmd
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd
        
# Personalize the colours in your website. 
# Colour values can be any valid CSS colour

page-col: "#E0FCDD"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#93F489"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#93F489"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

             


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

