project:
  type: website

website:
  page-navigation: true
  title: "akmsquarto"
  
  page-footer:
    center: "Built with ❤️ and powered by Quarto"
    left: "&copy; CC-By CWB, 2024"
  
  
  sidebar:
    logo: "images/cwd/1.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://github.com/arunmhh
        text: "arunmhh"
      - icon: github
        href: https://github.com/arunmhh/akmsquarto
        text: "Quartoarun"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Quartoinformation
      - href: linearregression.qmd
        text: linear regression
      - section: quarto-workflows/index.qmd
        contents: 
          - quarto-workflows/browser.md
          - quarto-workflows/rstudio.qmd
          - quarto-workflows/jupyter.md 
      - learning-more.qmd
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd

             


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

